//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_PSSC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PSSCEntities : DbContext
    {
        public PSSCEntities()
            : base("name=PSSCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TABELA_CONSULTATIE> TABELA_CONSULTATIE { get; set; }
        public virtual DbSet<TABELA_MEDIC> TABELA_MEDIC { get; set; }
    }
}
