//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_PSSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABELA_MEDIC
    {
        public string ID_MEDIC { get; set; }
        public string NUME_MEDIC { get; set; }
    }
}
