//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_PSSC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABELA_CONSULTATIE
    {
        public int ID_CONSULTATIE { get; set; }
        public Nullable<int> CABINET { get; set; }
        public Nullable<int> ID_MEDIC { get; set; }
        public string PROBLEMA { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string ORA { get; set; }
    }
}
